apps/accounts/urls.py
from django.urls import path,include
from .views import PatientSignupView,EmployeeSignupView,LoginAccountView,LogoutUserView


app_name = 'accounts'

urlpatterns = [
    path('patient/register/', PatientSignupView.as_view(),name='patient-signup'),
    path('employee/register/', EmployeeSignupView.as_view(),name='employee-signup'),
    path('', LoginAccountView.as_view(),name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
]

apps/ailment/urls.py
from django.urls import path,include
from .views import (AllAilmentsView,CreateAilmentsView,UpdateAilmentsView,DeleteAilmentsView
                    )


app_name = 'ailments'

urlpatterns = [
    path('all-ailments/', AllAilmentsView.as_view(),name='all-ailments'),
    path('create-ailment/', CreateAilmentsView.as_view(),name='create-ailment'),
    path('update-ailment/<str:slug>/', UpdateAilmentsView.as_view(),name='update-ailment'),
    path('delete-ailment/<str:slug>/', DeleteAilmentsView.as_view(),name='delete-ailment'),
 
]

apps/course/urls.py
from django.urls import path,include
from .views import (AllCoursesView,CreateCourseView,UpdateCourseView,DeleteCourseView)


app_name = 'courses'

urlpatterns = [
    path('all-courses/', AllCoursesView.as_view(),name='all-courses'),
    path('create-course/',CreateCourseView.as_view(),name='create-course'),
    path('update-course/<str:slug>/', UpdateCourseView.as_view(),name='update-course'),
    path('delete-course/<str:slug>/',DeleteCourseView.as_view(),name='delete-course'),
 
]

apps/profiles/urls.py
from django.urls import path,include
from .views import (PatientProfileView,PatientUpdateProfileView,EmployeeProfileView,EmployeeUpdateProfileView,AllDoctorsView,AllEmployeesView,AllPatientsView)


app_name = 'profiles'

urlpatterns = [
     path('all-patients/', AllPatientsView.as_view(),name='all-patients'),
    path('all-employees/', AllEmployeesView.as_view(),name='all-employees'),
    path('all-doctors/', AllDoctorsView.as_view(),name='all-doctors'),
    path('patient-profile/<str:slug>/', PatientProfileView.as_view(),name='patient-profile'),
    path('patient-update-profile/<str:slug>/', PatientUpdateProfileView.as_view(),name='patient-update-profile'),
    path('employee-profile/<str:slug>/', EmployeeProfileView.as_view(),name='employee-profile'),
    path('employee-update-profile/<str:slug>/', EmployeeUpdateProfileView.as_view(),name='employee-update-profile'),
]

preclinic/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls',namespace='accounts')),
    path('profiles/', include('apps.profiles.urls',namespace='profiles')),
    path('utilities/', include('apps.utilities.urls',namespace='utilities')),
    path('appointments/', include('apps.appointments.urls',namespace='appointments')),
    path('ailment/', include('apps.ailment.urls',namespace='ailments')),
    path('course/', include('apps.course.urls',namespace='courses')),
    path('departments/', include('apps.departments.urls',namespace='departments')),
    path('institution/', include('apps.institution.urls',namespace='institutions')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/alert.html
{% block content %}
{% if messages %}
    {% for message in messages %}
        {% if message.tags == "danger" %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
        {% else %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">



<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">
    <title>Preclinic - Medical & Hospital - Bootstrap 4 Admin Template</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/modified-style.css' %}">
    <!--[if lt IE 9]>
		<script src="assets/js/html5shiv.min.js"></script>
		<script src="assets/js/respond.min.js"></script>
	<![endif]-->
</head>

<body>
    <div class="main-wrapper">
        {% include 'header.html' %}
        {% include 'sidebar.html' %}
       
        <div class="page-wrapper">
            
            {% block content %}
                
            {% endblock content %}
              
        
        </div>
    </div>
    <div class="sidebar-overlay" data-reff=""></div>
    <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.slimscroll.js' %}"></script>
    <script src="{% static 'assets/js/Chart.bundle.js' %}"></script>
    <script src="{% static 'assets/js/chart.js' %}"></script>
    <script src="{% static 'assets/js/app.js' %}"></script>
    <!-- <script src="{% static 'assets/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.dataTables.min.js' %}"></script> -->

</body>



</html>

templates/base_auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- register24:03-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">
    <title>Preclinic - Medical & Hospital </title>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/modified-style.css' %}">
    <!--[if lt IE 9]>
		<script src="assets/js/html5shiv.min.js"></script>
		<script src="assets/js/respond.min.js"></script>
	<![endif]-->
</head>

<body>
    <div class="main-wrapper  account-wrapper">
       
       {% block content %}
        
       {% endblock content %}
        
    </div>
    <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.slimscroll.js' %}"></script>
    <script src="{% static 'assets/js/Chart.bundle.js' %}"></script>
    <script src="{% static 'assets/js/chart.js' %}"></script>
    <script src="{% static 'assets/js/app.js' %}"></script>
</body>


<!-- register24:03-->
</html>

templates/header.html
{% block content %}
{% load static %}
<div class="header">
    <div class="header-left">
        <a href="index-2.html" class="logo">
            <img src="{% static 'assets/img/logo.png' %}" width="35" height="35" alt=""> <span>Preclinic</span>
        </a>
    </div>
    <a id="toggle_btn" href="javascript:void(0);"><i class="fa fa-bars"></i></a>
    <a id="mobile_btn" class="mobile_btn float-left" href="#sidebar"><i class="fa fa-bars"></i></a>
    <ul class="nav user-menu float-right">
        <li class="nav-item dropdown has-arrow">
            <a href="#" class="dropdown-toggle nav-link user-link" data-toggle="dropdown">
                <span class="user-img">
                    {% if request.user.is_patient %}
                    <img class="rounded-circle" src="{{request.user.patient.profile_picture_url}}" width="24" alt="Admin">
                    {% elif request.user.is_employee %}                        
                    <img class="rounded-circle" src="{{request.user.employee.profile_picture_url}}" width="24" alt="Admin">
                    {% endif %}
                        
                    <span class="status online"></span>
                </span>
                <span>{{request.user.full_name}}</span>
            </a>
            <div class="dropdown-menu">
                
                {% if request.user.is_patient %}
                <a class="dropdown-item" href="{% url 'profiles:patient-profile' request.user.patient.slug %}">My Profile</a>
                <a class="dropdown-item" href="{% url 'profiles:patient-update-profile' request.user.patient.slug %}">Edit Profile</a>
                {% elif request.user.is_employee %}
                <a class="dropdown-item" href="{% url 'profiles:employee-profile' request.user.employee.slug %}">My Profile</a>
                <a class="dropdown-item" href="{% url 'profiles:employee-update-profile' request.user.employee.slug %}">Edit Profile</a>
                {% endif   %}
                                    
                {% if request.user.is_authenticated %}
                    
                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                {% endif %}
                    
            </div>
        </li>
    </ul>
    <div class="dropdown mobile-user-menu float-right">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
        <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="profile.html">My Profile</a>
            <a class="dropdown-item" href="edit-profile.html">Edit Profile</a>
            <a class="dropdown-item" href="settings.html">Settings</a>
            <a class="dropdown-item" href="login.html">Logout</a>
        </div>
    </div>
</div>
{% endblock content %}
    

templates/sidebar.html
{% block content %}
<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <ul>
                <li class="menu-title">Main</li>
                {% if request.user.is_patient and request.user.patient.has_updated_profile %}
               
                <li class="{% if request.resolver_match.url_name == 'patient-home-view' %}  active {% endif %}">
                    <a href="{% url 'appointments:patient-home-view' %}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a>
                </li>        
                <li class="submenu">
                    <a  href="#"><i class="fa fa-calendar"></i> <span> Appointments</span> <span class="menu-arrow"></span></a>
                    <ul style="display: none;">
                        <li class="{% if request.resolver_match.url_name == 'all-patient-appointments' %} active {% endif %}" ><a href="{% url 'appointments:all-patient-appointments' %}">All Appointments</a></li>
                        <li  class="{% if request.resolver_match.url_name == 'pending-patient-appointments' %} active {% endif %}"><a href="{% url 'appointments:pending-patient-appointments' %}">Pending Appointments</a></li>
                        <li  class="{% if request.resolver_match.url_name == 'approved-patient-appointments' %} active {% endif %}"><a href="{% url 'appointments:approved-patient-appointments' %}">Approved Appointments</a></li>
                        <li  class="{% if request.resolver_match.url_name == 'completed-patient-appointments' %} active {% endif %}"><a href="{% url 'appointments:completed-patient-appointments' %}">Completed Appointments</a></li>
                    </ul>
                </li>
                <li class="{% if request.resolver_match.url_name == 'create-patient-appointment' %}  active {% endif %}" >
                    <a href="{% url 'appointments:create-patient-appointment' %}"><i class="fa fa-edit"></i> <span>Create Appointment</span></a>
                </li>
                <li class="{% if request.resolver_match.url_name == 'patient-profile' %}  active {% endif %}">
                    <a href="{% url 'profiles:patient-profile' request.user.patient.slug %}"><i class="fa fa-user-md"></i> <span>Profile</span></a>
                </li>    
                <li class="{% if request.resolver_match.url_name == 'patient-update-profile' %}  active {% endif %}">
                    <a href="{% url 'profiles:patient-update-profile' request.user.patient.slug %}"><i class="fa fa-user-md"></i> <span>Update Profile</span></a>
                </li>    
                {% elif request.user.is_employee and request.user.employee.role == 'Doctor' and request.user.patient.has_updated_profile %}
                
                <li class="{% if request.resolver_match.url_name == 'doctor-home-view' %}  active {% endif %}">
                    <a href="{% url 'appointments:doctor-home-view' %}"><i class="fa fa-dashboard"></i><span>Dashboard</span></a>
                </li>        
                <li class="submenu">
                    <a  href="#"><i class="fa fa-calendar"></i> <span> Appointments</span> <span class="menu-arrow"></span></a>
                    <ul style="display: none;">
                        <li class="{% if request.resolver_match.url_name == 'all-doctor-appointments' %} active {% endif %}" ><a href="{% url 'appointments:all-doctor-appointments' %}">All Appointments</a></li>
                        <li  class="{% if request.resolver_match.url_name == 'pending-doctor-appointments' %} active {% endif %}"><a href="{% url 'appointments:pending-doctor-appointments' %}">Pending Appointments</a></li>
                        <li  class="{% if request.resolver_match.url_name == 'approved-doctor-appointments' %} active {% endif %}"><a href="{% url 'appointments:approved-doctor-appointments' %}">Approved Appointments</a></li>
                        <li  class="{% if request.resolver_match.url_name == 'completed-doctor-appointments' %} active {% endif %}"><a href="{% url 'appointments:completed-doctor-appointments' %}">Completed Appointments</a></li>
                    </ul>
                </li>
                
                            
                
                
                {% elif request.user.is_staff %} 
                
                <li class="{% if request.resolver_match.url_name == 'staff-home-view' %}  active {% endif %}">
                    <a href="{% url 'appointments:staff-home-view' %}"><i class="fa fa-dashboard"></i><span>Dashboard</span></a>
                </li>        
                <li class="submenu">
                    <a  href="#"><i class="fa fa-calendar"></i> <span> Appointments</span> <span class="menu-arrow"></span></a>
                    <ul style="display: none;">
                        <li class="{% if request.resolver_match.url_name == 'all-staff-appointments' %} active {% endif %}" ><a href="{% url 'appointments:all-staff-appointments' %}">All Appointments</a></li>
                        <li  class="{% if request.resolver_match.url_name == 'pending-staff-appointments' %} active {% endif %}"><a href="{% url 'appointments:pending-staff-appointments' %}">Pending Appointments</a></li>
                        <li  class="{% if request.resolver_match.url_name == 'approved-staff-appointments' %} active {% endif %}"><a href="{% url 'appointments:approved-staff-appointments' %}">Approved Appointments</a></li>
                        <li  class="{% if request.resolver_match.url_name == 'completed-staff-appointments' %} active {% endif %}"><a href="{% url 'appointments:completed-staff-appointments' %}">Completed Appointments</a></li>
                    </ul>
                </li>
                <li class="{% if request.resolver_match.url_name == 'all-doctors' %}  active {% endif %}">
                    <a href="{% url 'profiles:all-doctors' %}"><i class="fa fa-user-md"></i> <span>Doctors</span></a>
                </li>    
                <li class="{% if request.resolver_match.url_name == 'all-employees' %}  active {% endif %}">
                    <a href="{% url 'profiles:all-employees' %}"><i class="fa fa-user-o"></i> <span>Employees</span></a>
                </li>    
                <li class="{% if request.resolver_match.url_name == 'all-patients' %}  active {% endif %}">
                    <a href="{% url 'profiles:all-patients'  %}"><i class="fa fa-wheelchair"></i> <span>Patients</span></a>
                </li>    
                <li class="{% if request.resolver_match.url_name == 'all-ailments' %}  active {% endif %}">
                    <a href="{% url 'ailments:all-ailments'  %}"><i class="fa fa-hospital-o"></i> <span>Ailments</span></a>
                </li>    
                <li class="{% if request.resolver_match.url_name == 'all-courses' %}  active {% endif %}">
                    <a href="{% url 'courses:all-courses'  %}"><i class="fa fa-book"></i> <span>Courses</span></a>
                </li>    
                <li class="{% if request.resolver_match.url_name == 'all-departments' %}  active {% endif %}">
                    <a href="{% url 'departments:all-departments'  %}"><i class="fa fa-hospital-o"></i> <span>Departments</span></a>
                </li>    
                <li class="{% if request.resolver_match.url_name == 'all-institutions' %}  active {% endif %}">
                    <a href="{% url 'institutions:all-institutions'  %}"><i class="fa fa-cube"></i> <span>Institutions</span></a>
                </li>    

               {% endif %}
               
               {% if request.user.is_employee and request.user.employee.has_updated_profile %}
               <li class="{% if request.resolver_match.url_name == 'general-employee-view-for-all-employees' %}  active {% endif %}">
                <a href="{% url 'appointments:general-employee-view-for-all-employees' %}"><i class="fa fa-dashboard"></i><span>Dashboard</span></a>
                </li>        
              
                <li class="{% if request.resolver_match.url_name == 'employee-profile' %}  active {% endif %}">
                    <a href="{% url 'profiles:employee-profile' request.user.employee.slug %}"><i class="fa fa-user-md"></i> <span>Profile</span></a>
                </li>    
                <li class="{% if request.resolver_match.url_name == 'employee-update-profile' %}  active {% endif %}">
                    <a href="{% url 'profiles:employee-update-profile' request.user.employee.slug %}"><i class="fa fa-user-md"></i> <span>Update Profile</span></a>
                </li>    
               {% endif %}
                
                    
               
            </ul>
        </div>
    </div>
</div>
{% endblock content %}
    