apps/institution/urls.py
from django.urls import path
from .views import (AllInstitutionsView,CreateInstitutionView,UpdateInstitutionView,DeleteInstitutionView)


app_name = 'institutions'

urlpatterns = [
    path('all-institutions/', AllInstitutionsView.as_view(),name='all-institutions'),
    path('create-institution/',CreateInstitutionView.as_view(),name='create-institution'),
    path('update-institution/<str:slug>/', UpdateInstitutionView.as_view(),name='update-institution'),
    path('delete-institution/<str:slug>/',DeleteInstitutionView.as_view(),name='delete-institution'),
 
]

preclinic/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls',namespace='accounts')),
    path('profiles/', include('apps.profiles.urls',namespace='profiles')),
    path('utilities/', include('apps.utilities.urls',namespace='utilities')),
    path('appointments/', include('apps.appointments.urls',namespace='appointments')),
    path('ailment/', include('apps.ailment.urls',namespace='ailments')),
    path('course/', include('apps.course.urls',namespace='courses')),
    path('departments/', include('apps.departments.urls',namespace='departments')),
    path('institution/', include('apps.institution.urls',namespace='institutions')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/institution/models.py
from django.db import models
from autoslug import  AutoSlugField
import uuid

class Institution(models.Model):
    pkid = models.BigAutoField(primary_key=True, editable=False)
    id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=260,unique=True,verbose_name="Name of Institution")
    slug = AutoSlugField(populate_from='name', unique=True)

    class Meta:
        verbose_name = "Institution"
        verbose_name_plural = "Institutions"

    def __str__(self):
        return self.name

apps/institution/forms.py
from django.forms import ModelForm
from .models import Institution

class InstitutionForm(ModelForm):
    
    class Meta:
        model = Institution
        fields=['name']

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})




        

apps/institution/views.py
from django.shortcuts import render
from django.contrib.messages.views import SuccessMessageMixin
from .models import Institution
from django.contrib.auth.mixins import LoginRequiredMixin
from apps.profiles.custom_permissions import UserIsStaffMixin
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from .forms import InstitutionForm

# Create your views here.
class AllInstitutionsView(LoginRequiredMixin,UserIsStaffMixin,ListView):
    model = Institution
    template_name = 'institutions/all_institutions.html'
    context_object_name='institutions'
    paginate_by = 10

    

class CreateInstitutionView(LoginRequiredMixin,UserIsStaffMixin,SuccessMessageMixin,CreateView):
    model = Institution
    form_class=InstitutionForm
    success_message = 'institution successfully created'
    success_url = reverse_lazy('institutions:all-institutions')
    template_name = 'institutions/create_institution.html'
    context_object_name='institution'
    
    

class UpdateInstitutionView(LoginRequiredMixin,UserIsStaffMixin,SuccessMessageMixin,UpdateView):
    model = Institution
    form_class=InstitutionForm
    template_name = 'institutions/update_institution.html'
    success_message = 'institution successfully updated'
    success_url = reverse_lazy('institutions:all-institutions')
    context_object_name='institution'
   

class DeleteInstitutionView(LoginRequiredMixin,UserIsStaffMixin,SuccessMessageMixin,DeleteView):
    model = Institution
    success_message = 'institution successfully deleted'
    success_url = reverse_lazy('institutions:all-institutions')
    

    

apps/institution/templates/institutions/all_institutions.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="content">
    <div class="row">
        <div class="col-sm-5 col-5">
            <h4 class="page-title">Institution</h4>
        </div>
        <div class="col-sm-7 col-7 text-right m-b-30">
            <a href="{% url 'institutions:create-institution' %}" class="btn btn-primary btn-rounded"><i class="fa fa-plus"></i> Create Institution</a>
        </div>
    </div>
    {% include 'alert.html' %}

    {% if institutions %}

    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                
                <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                   
                    <div class="dataTables_length" id="DataTables_Table_0_length">
                        </div>
                            <table class="table table-striped custom-table mb-0 datatable dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
                    <thead>
                        <tr role="row"><th class="sorting_desc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="#: activate to sort column ascending" style="width: 87.8438px;" aria-sort="descending">#</th>
                            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Institution Name: activate to sort column ascending" style="width: 396.391px;">Ailment Name</th>
                           
                            <th class="text-right sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Action: activate to sort column ascending" style="width: 184.234px;">Action</th></tr>
                    </thead>
                    <tbody>
                        {% for institution in institutions %}
                        <tr role="row" class="odd">
                            <td class="sorting_1">{{institution.pkid}}</td>
                            <td>{{institution.name}}</td>
                            <td class="text-right">
                                <div class="dropdown dropdown-action">
                                    <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="{% url 'institutions:update-institution' institution.slug %}"><i class="fa fa-pencil m-r-5"></i> Edit</a>
                                        <a class="dropdown-item" href="{% url 'institutions:delete-institution' institution.slug %}" data-toggle="modal" data-target="#delete_institution-{{institution.slug}}"><i class="fa fa-trash-o m-r-5"></i> Delete</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}     
                    </tbody>
                </table>
                <div class="row">
                    <div class="col-sm-12 col-md-5">
                        <div class="dataTables_info" role="status" aria-live="polite">
                            Showing {{ page_obj.start_index }} to {{ page_obj.end_index }} of {{ page_obj.paginator.count }} entries
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-7">
                        <div class="dataTables_paginate paging_simple_numbers">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="paginate_button page-item">
                                        <a href="?page=1" aria-label="First" class="page-link">First</a>
                                    </li>
                                    <li class="paginate_button page-item">
                                        <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous" class="page-link">Previous</a>
                                    </li>
                                {% endif %}
                
                                {% for num in page_obj.paginator.page_range %}
                                    <li class="paginate_button page-item {% if num == page_obj.number %}active{% endif %}">
                                        <a href="?page={{ num }}" class="page-link">{{ num }}</a>
                                    </li>
                                {% endfor %}
                
                                {% if page_obj.has_next %}
                                    <li class="paginate_button page-item">
                                        <a href="?page={{ page_obj.next_page_number }}" aria-label="Next" class="page-link">Next</a>
                                    </li>
                                    <li class="paginate_button page-item">
                                        <a href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last" class="page-link">Last</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
                
                               
            </div>
        </div>
        
    </div>

    {% for institution in institutions %}
    <div id="delete_institution-{{institution.slug}}" class="modal fade delete-modal" role="dialog">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <img src="{% static 'assets/img/sent.png' %}" alt="" width="50" height="46">
                    <h3>Are you sure want to delete this institution?</h3>
                    <p>{{institution.name|title}}</p>
                    <form action="{% url 'institutions:delete-institution' institution.slug %}" method="POST">
                        {% csrf_token %}
                        <div   div class="m-t-20"> <a href="#" class="btn btn-white" data-dismiss="modal">Close</a>
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    
    
    
</div>
{% else %}
<h3 class="font-weight-light" >No institution available</h3>

{% endif %}


{% endblock content %}
    

apps/institution/templates/institutions/create_institution.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="content">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <h4 class="page-title">Create Course</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <form method="POST" action="{% url 'institutions:create-institution' %}" >
                {% csrf_token %}
                {{form.as_p}}
                <div class="m-t-20 text-center">
                    <button class="btn btn-primary submit-btn">Create Institution</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}
    

apps/institution/templates/institutions/update_institution.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="content">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <h4 class="page-title">Update Course</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <form method="POST" action="{% url 'institutions:update-institution' institution.slug %}" >
                {% csrf_token %}
                {{form.as_p}}
                <div class="m-t-20 text-center">
                    <button class="btn btn-primary submit-btn">Update Institution</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}
    