apps/appointments/urls.py
from django.urls import path,include
from .views import (PatientHomeView,PatientCreateAppointmentView,PatientDeleteAppointmentView,
                    PatientUpdateAppointmentView,PatientDetailAppointmentView,AllPatientAppointmentsView,
                    PendingPatientAppointmentsView,ApprovedPatientAppointmentsView,CompletedPatientAppointmentsView,
                    DoctorHomeView,AllDoctorAppointmentsView,PendingDoctorAppointmentsView,UpcomingDoctorAppointmentsView,
                    CompletedDoctorAppointmentsView,DoctorDetailAppointmentView,DoctorUpdateAppointmentView,
                    StaffHomeView,AllAppointmentsStaffView,PendingStaffAppointmentsView,CompletedStaffAppointmentsView,ApprovedStaffAppointmentsView,
                    StaffDetailAppointmentView,StaffUpdateAppointmentView,GeneralEmployeeViewForNonDoctors
                    )


app_name = 'appointments'

admin_patterns = [
    path('staff-home/', StaffHomeView.as_view(),name='staff-home-view'),
    path('all-appointments/', AllAppointmentsStaffView.as_view(),name='all-staff-appointments'),
    path('pending-staff-appointments/', PendingStaffAppointmentsView.as_view(),name='pending-staff-appointments'),
    path('approved-staff-appointments/', ApprovedStaffAppointmentsView.as_view(),name='approved-staff-appointments'),
    path('completed-staff-appointments/', CompletedStaffAppointmentsView.as_view(),name='completed-staff-appointments'),
    path('get-staff-appointment/<str:slug>/', StaffDetailAppointmentView.as_view(),name='staff-appointment-detail'),
    path('update-staff-appointment/<str:slug>/', StaffUpdateAppointmentView.as_view(),name='update-staff-appointment'),
    # path('delete-staff-appointment/<str:slug>/', StaffDeleteAppointmentView.as_view(),name='delete-staff-appointment'),
]

patient_patterns = [
    path('patient-home/', PatientHomeView.as_view(),name='patient-home-view'),
    path('all-patient-appointments/', AllPatientAppointmentsView.as_view(),name='all-patient-appointments'),
    path('pending-patient-appointments/', PendingPatientAppointmentsView.as_view(),name='pending-patient-appointments'),
    path('approved-patient-appointments/', ApprovedPatientAppointmentsView.as_view(),name='approved-patient-appointments'),
    path('completed-patient-appointments/', CompletedPatientAppointmentsView.as_view(),name='completed-patient-appointments'),
    path('create-patient-appointment/', PatientCreateAppointmentView.as_view(),name='create-patient-appointment'),
    path('get-patient-appointment/<str:slug>/', PatientDetailAppointmentView.as_view(),name='patient-appointment-detail'),
    path('update-patient-appointment/<str:slug>/', PatientUpdateAppointmentView.as_view(),name='update-patient-appointment'),
    path('delete-patient-appointment/<str:slug>/', PatientDeleteAppointmentView.as_view(),name='delete-patient-appointment'),
]
doctor_patterns = [
    path('doctor-home/', DoctorHomeView.as_view(),name='doctor-home-view'),
    path('all-doctor-appointments/', AllDoctorAppointmentsView.as_view(),name='all-doctor-appointments'),
    path('pending-doctor-appointments/', PendingDoctorAppointmentsView.as_view(),name='pending-doctor-appointments'),
    path('approved-doctor-appointments/', UpcomingDoctorAppointmentsView.as_view(),name='approved-doctor-appointments'),
    path('completed-doctor-appointments/', CompletedDoctorAppointmentsView.as_view(),name='completed-doctor-appointments'),
    path('get-doctor-appointment/<str:slug>/', DoctorDetailAppointmentView.as_view(),name='doctor-appointment-detail'),
    path('update-doctor-appointment/<str:slug>/', DoctorUpdateAppointmentView.as_view(),name='update-doctor-appointment'),
   
]

employee_patterns = [
    path('general-employee-view-for-all-employees/', GeneralEmployeeViewForNonDoctors.as_view(),name='general-employee-view-for-all-employees'),

]

urlpatterns = patient_patterns + doctor_patterns + admin_patterns + employee_patterns

preclinic/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls',namespace='accounts')),
    path('profiles/', include('apps.profiles.urls',namespace='profiles')),
    path('utilities/', include('apps.utilities.urls',namespace='utilities')),
    path('appointments/', include('apps.appointments.urls',namespace='appointments')),
    path('ailment/', include('apps.ailment.urls',namespace='ailments')),
    path('course/', include('apps.course.urls',namespace='courses')),
    path('departments/', include('apps.departments.urls',namespace='departments')),
    path('institution/', include('apps.institution.urls',namespace='institutions')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/appointments/forms.py
from .models import AdminAppointment,Appointment,DoctorAppointment
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils import timezone
from apps.profiles.models import Employee
class PatientAppointmentForm(ModelForm):
    
    class Meta:

        model = Appointment
        exclude=['ref','created_by','completed']

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['appointment_date'].widget.attrs.update({'class': 'form-control'})
        self.fields['department'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'class': 'form-control'})

    def clean_appointment_date(self):
        appointment_date = self.cleaned_data['appointment_date']
        if appointment_date  and appointment_date < timezone.now().date()+ timezone.timedelta(days=1):
            raise ValidationError("You can't create an appointment before today. You can only book an appointment from tomorrow onwards")
        return appointment_date

class AdminAppointmentForm(ModelForm):
    
    class Meta:

        model = AdminAppointment
        exclude=['ref','appointment']

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields['start_time'].widget.attrs.update({'class': 'form-control'})
        self.fields['end_time'].widget.attrs.update({'class': 'form-control'})
        self.fields['cost'].widget.attrs.update({'class': 'form-control'})
        self.fields['status'].widget.attrs.update({'class': 'form-control'})
        self.fields['employee'].widget.attrs.update({'class': 'form-control'})

     
        self.fields['employee'].queryset = Employee.objects.filter(role='Doctor')

    def clean_employee(self):
        employee = self.cleaned_data.get('employee')
        if employee and not employee.role == 'Doctor':
            raise ValidationError("Only doctors can be assigned to appointments.")
        return employee


class DoctorAppointmentForm(ModelForm):
    
    class Meta:

        model = DoctorAppointment
        exclude=['ref','appointment']

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields['symptoms'].widget.attrs.update({'class': 'form-control'})
        self.fields['recommendation'].widget.attrs.update({'class': 'form-control'})
        self.fields['drugs'].widget.attrs.update({'class': 'form-control'})
       
        

apps/appointments/views.py
from typing import Any, Dict, Optional
from django.db import models
from django.db.models.query import QuerySet
from django.shortcuts import render,get_object_or_404
from django.views.generic import TemplateView,ListView,CreateView,UpdateView,DeleteView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Appointment,DoctorAppointment,AdminAppointment
from apps.profiles.models import Employee,Patient
from django.utils import timezone
# from apps.appointments.models import AdminAppointment
from django.db.models import Sum,Count
from datetime import date
# from .custom_permissions import UserIsEmployeeMixin,UserIsPatientMixin
# LoginRequiredMixin,
from datetime import datetime
from django.contrib.messages.views import SuccessMessageMixin
from .forms import PatientAppointmentForm,DoctorAppointmentForm,AdminAppointmentForm
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from apps.profiles.custom_permissions import UserIsEmployeeMixin,UserIsPatientMixin,UserIsDoctorMixin,UserIsStaffMixin


#  --------------------------------------------------- Patient Views ---------------------------------------------------------

class PatientHomeView(LoginRequiredMixin,UserIsPatientMixin,TemplateView):
    template_name= 'appointments/patients/index.html'
    context_object_name="appointments"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        patient_profile = get_object_or_404(Patient,user=self.request.user)
        total_amount_spent = Appointment.objects.filter(created_by=patient_profile).aggregate(Sum("adminappointment__cost"))['adminappointment__cost__sum']
        pending_appointments_count = Appointment.objects.filter(created_by=patient_profile,adminappointment__status='Pending').count()
        approved_appointments_count = Appointment.objects.filter(created_by=patient_profile,adminappointment__status='Approved').count()
        completed_appointments_count = Appointment.objects.filter(created_by=patient_profile,adminappointment__status='Completed').count()
        
        
        pending_appointments = Appointment.objects.filter(created_by=patient_profile,adminappointment__status='Pending')[0:5]
        completed_appointments = Appointment.objects.filter(created_by=patient_profile,adminappointment__status='Completed')[0:5]
        approved_appointments = Appointment.objects.filter(created_by=patient_profile,adminappointment__status='Approved')[0:5]
        
        context['pending_appointments_count'] = pending_appointments_count
        context['approved_appointments_count'] = approved_appointments_count
        context['completed_appointments_count'] = completed_appointments_count
        context['total_amount_spent'] =total_amount_spent

        context['pending_appointments'] =pending_appointments
        context['completed_appointments'] =completed_appointments
        context['approved_appointments'] =approved_appointments
        return context
    
class AllPatientAppointmentsView(LoginRequiredMixin,UserIsPatientMixin,ListView):
    model = Appointment
    template_name = 'appointments/patients/all_patient_appointment.html'
    context_object_name='appointments'
    paginate_by = 10

    def get_queryset(self):
        patient_profile = get_object_or_404(Patient,user=self.request.user)
        appointments = Appointment.objects.filter(created_by=patient_profile)
        return appointments
    
class PendingPatientAppointmentsView(LoginRequiredMixin,UserIsPatientMixin,ListView):
    model = Appointment
    template_name = 'appointments/patients/all_patient_appointment.html'
    context_object_name='appointments'
    paginate_by = 10

    def get_queryset(self):
        patient_profile = get_object_or_404(Patient,user=self.request.user)
        appointments = Appointment.objects.filter(created_by=patient_profile,adminappointment__status='Pending')
        return appointments
    
class ApprovedPatientAppointmentsView(LoginRequiredMixin,UserIsPatientMixin,ListView):
    model = Appointment
    template_name = 'appointments/patients/all_patient_appointment.html'
    context_object_name='appointments'
    paginate_by = 10

    def get_queryset(self):
        patient_profile = get_object_or_404(Patient,user=self.request.user)
        appointments = Appointment.objects.filter(created_by=patient_profile,adminappointment__status='Approved')
        return appointments
    
class CompletedPatientAppointmentsView(LoginRequiredMixin,UserIsPatientMixin,ListView):
    model = Appointment
    template_name = 'appointments/patients/all_patient_appointment.html'
    context_object_name='appointments'
    paginate_by = 10

    def get_queryset(self):
        patient_profile = get_object_or_404(Patient,user=self.request.user)
        appointments = Appointment.objects.filter(created_by=patient_profile,adminappointment__status='Completed')
        return appointments
    
class PatientCreateAppointmentView(LoginRequiredMixin,UserIsPatientMixin,SuccessMessageMixin,CreateView):
    form_class = PatientAppointmentForm
    success_message = 'appointment successfully created'
    success_url = reverse_lazy('appointments:all-patient-appointments')
    template_name = 'appointments/patients/patient_create_appointment.html'
    
    def form_valid(self, form):
        patient_profile = get_object_or_404(Patient,user=self.request.user)
        form.instance.created_by = patient_profile
        return super().form_valid(form)
    

    # def get_form_kwargs(self):
    #     kwargs = super(PatientAppointmentForm, self).get_form_kwargs()
    #     if kwargs['created_by'] is None:
    #         patient_profile = get_object_or_404(Patient,user=self.request.user)
    #     kwargs['instance'].created_by = patient_profile
    #     return kwargs
    
class PatientDetailAppointmentView(LoginRequiredMixin,UserIsPatientMixin,DetailView):
    model = Appointment
    success_url = reverse_lazy('appointments:all-patient-appointments')
    template_name = 'appointments/patients/patient_appointment_detail.html'

    def get_object(self, queryset=None):
        obj = super(PatientDetailAppointmentView, self).get_object()
        if not obj.created_by.user == self.request.user:
            raise PermissionDenied(
                "You don't have permission to view an appointment you didn't create")
        return obj
    
class PatientUpdateAppointmentView(LoginRequiredMixin,UserIsPatientMixin,SuccessMessageMixin,UpdateView):
    model=Appointment
    form_class = PatientAppointmentForm
    success_message = 'Appointment successfully updated'
    success_url = reverse_lazy('appointments:all-patient-appointments')
    template_name = 'appointments/patients/patient_update_appointment.html'

    def get_object(self, queryset=None):
        obj = super(PatientUpdateAppointmentView, self).get_object()
        if not obj.created_by.user == self.request.user:
            raise PermissionDenied(
                "You don't have permission to update an appointment you didn't create")
        return obj
    
class PatientDeleteAppointmentView(LoginRequiredMixin,UserIsPatientMixin,SuccessMessageMixin,DeleteView):
    model = Appointment
    success_message = 'appointment successfully deleted'
    success_url = reverse_lazy('appointments:all-patient-appointments')

    def get_object(self, queryset=None):
        obj = super().get_object()
        if not obj.created_by.user == self.request.user:
            raise PermissionDenied("You don't have permission to delete an appointment you didn't create")
        return obj




#  --------------------------------------------------- General Employee View ---------------------------------------------------------

class GeneralEmployeeViewForNonDoctors(LoginRequiredMixin,UserIsEmployeeMixin,TemplateView):
    template_name= 'appointments/employee/general_employee.html'
    

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
       
        return context
    
#  --------------------------------------------------- Doctor Views ---------------------------------------------------------

class DoctorHomeView(LoginRequiredMixin,UserIsDoctorMixin,TemplateView):
    template_name= 'appointments/employee/index.html'
    context_object_name="appointments"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        doctor_profile = get_object_or_404(Employee,user=self.request.user,role='Doctor')
        pending_appointments_count = Appointment.objects.filter(adminappointment__employee=doctor_profile,adminappointment__status='Pending').count()
        upcoming_appointments_count = Appointment.objects.filter(adminappointment__employee=doctor_profile,adminappointment__status='Approved').count()
        completed_appointments_count = Appointment.objects.filter(adminappointment__employee=doctor_profile,adminappointment__status='Completed').count()
        
        
        pending_appointments = Appointment.objects.filter(adminappointment__employee=doctor_profile,adminappointment__status='Pending')[0:5]
        completed_appointments = Appointment.objects.filter(adminappointment__employee=doctor_profile,adminappointment__status='Completed')[0:5]
        upcoming_appointments = Appointment.objects.filter(adminappointment__employee=doctor_profile,adminappointment__status='Approved')[0:5]
        
        context['pending_appointments_count'] = pending_appointments_count
        context['upcoming_appointments_count'] = upcoming_appointments_count
        context['completed_appointments_count'] = completed_appointments_count
        
        context['pending_appointments'] =pending_appointments
        context['completed_appointments'] =completed_appointments
        context['upcoming_appointments'] =upcoming_appointments
        return context
    

apps/appointments/templates/appointments/employee/doctor_update_appointment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="content">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <h4 class="page-title">Update Appointment</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <form method="POST" action="{% url 'appointments:update-doctor-appointment' object.slug %}" >
                {% csrf_token %}
                {{form.as_p}}
                
             
                <div class="m-t-20 text-center">
                    <button  type="submit" class="btn btn-primary submit-btn">Update Appointment</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}
    

apps/appointments/templates/appointments/employee/general_employee.html
{% extends 'base.html' %}
{% block content %}
<div class="content">
    <div class="row">
      <h3>Welcome to our Employee General Page for all Employees</h3>
    </div>
   
  
</div>
{% endblock content %}
    

apps/appointments/templates/appointments/employee/index.html
{% extends 'base.html' %}
{% block content %}
<div class="content">
    <div class="row">
        <div class="col-md-6 col-sm-6 col-lg-6 col-xl-4">
            <div class="dash-widget">
                <span class="dash-widget-bg1"><i class="fa fa-stethoscope" aria-hidden="true"></i></span>
                <div class="dash-widget-info text-right">
                   
                    <h3>{{completed_appointments_count}}</h3>
                    <span class="widget-title1">Completed<i class="fa fa-check" aria-hidden="true"></i></span>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-sm-6 col-lg-6 col-xl-4">
            <div class="dash-widget">
                <span class="dash-widget-bg2"><i class="fa fa-user-o"></i></span>
                <div class="dash-widget-info text-right">
                    <h3>{{pending_appointments_count}}</h3>
                    <span class="widget-title2">Pending <i class="fa fa-check" aria-hidden="true"></i></span>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-sm-6 col-lg-6 col-xl-4">
            <div class="dash-widget">
                <span class="dash-widget-bg3"><i class="fa fa-user-md" aria-hidden="true"></i></span>
                <div class="dash-widget-info text-right">
                    <h3>{{upcoming_appointments_count}}</h3>
                    <span class="widget-title3">Upcoming <i class="fa fa-check" aria-hidden="true"></i></span>
                </div>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-12 col-md-6 col-lg-6 col-xl-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title d-inline-block">Pending Appointments </h4> <a href="{% url 'appointments:pending-doctor-appointments' %}" class="btn btn-primary float-right">View all</a>
                </div>
                <div class="card-body p-0">
                    <div class="table-responsive">
                        <table class="table mb-0">
                            <thead class="d-none">
                                <tr>
                                    <th>Id</th>
                                    <th>Date</th>
                                    <th>Timing </th>
                                </tr>
                            </thead>
                            
                            <tbody>
                                                              
                              {% for appointment in  pending_appointments %}                               
                                <tr>              
                                    <td>
                                        <h5 class="time-title p-0">ID</h5>
                                        <p>APT-{{appointment.pkid}}</p>
                                    </td>
                                    <td>
                                        <h5 class="time-title p-0">Appointment Date</h5>
                                        <p>{{appointment.appointment_date}}</p>
                                    </td>
                                    <td>
                                        <h5 class="time-title p-0">Timing</h5>
                                        <p>{{appointment.adminappointment.start_time}} - {{appointment.adminappointment.end_time}}</p>
                                    </td>
                                   
                                </tr>
                                {% empty %}
                                <tr>
                                    <td>
                                        <h5 class="font-weight-light" >No pending appointment</h5>
                                    </td>
                                </tr>
                             {% endfor %}                               
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-6 col-xl-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title d-inline-block">Approved Appointments</h4> <a href="{% url 'appointments:approved-doctor-appointments' %}" class="btn btn-primary float-right">View all</a>
                </div>
                <div class="card-body p-0">
                    <div class="table-responsive">
                        <table class="table mb-0">
                            <thead class="d-none">
                                <tr>
                                    <th>Patient Name</th>
                                    <th>Doctor Name</th>
                                    <th>Timing </th>
                                    
                                </tr>
                            </thead>
                            
                            <tbody>
                                
                                {% for appointment in approved_appointments %}
                                    
                                <tr>
                                    <td style="min-width: 200px;">
                                        <a class="avatar">{{appointment.department.name|slice:1}}</a>
                                        <h2><a href="departments.html">{{appointment.department}} <span>Department</span></a></h2>
                                    </td>                 
                                    <td>
                                        <h5 class="time-title p-0">Appointment With</h5>
                                        <p>Dr. {{appointment.adminappointment.employee.user.full_name}}</p>
                                    </td>
                                    <td>
                                        <h5 class="time-title p-0">Timing</h5>
                                        <p>{{appointment.adminappointment.start_time}} - {{appointment.adminappointment.end_time}}</p>
                                    </td>
                                   
                                </tr>
                                {% empty %}
                                <tr>
                                    <td>
                                        <h5 class="font-weight-light" >No approved appointment</h5>
                                    </td>
                                </tr>
                                {% endfor %}
                                
                                    
                               
                            </tbody>
                                
                        
                                
                        </table>
                    </div>
                </div>
            </div>
        </div>
       
    </div>
    <div class="row">
        <div class="col-12 col-md-12 col-lg-12 col-xl-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title d-inline-block">Completed Appointments </h4> <a href="{% url 'appointments:completed-doctor-appointments' %}" class="btn btn-primary float-right">View all</a>
                </div>
                <div class="card-block">
                    <div class="table-responsive">
                        <table class="table mb-0 new-patient-table">
                            <tbody>
                            
                            {% for appointment in completed_appointments %}
                                
                          
                                <tr>
                                    <td style="min-width: 200px;">
                                        <a class="avatar">{{appointment.department.name|slice:1}}</a>
                                        <h2><a href="departments.html">{{appointment.department}} <span>Department</span></a></h2>
                                    </td>                 
                                    <td>
                                        <h5 class="time-title p-0">Appointment With</h5>
                                        <p>Dr. {{appointment.adminappointment.employee.user.full_name}}</p>
                                    </td>
                                    <td>
                                        <h5 class="time-title p-0">Timing</h5>
                                        <p>{{appointment.adminappointment.start_time}} - {{appointment.adminappointment.end_time}}</p>
                                    </td>
                                    <td><button class="btn btn-primary btn-primary-one float-right">{{appointment.doctorappointment.ailment}}</button></td>
                                   
                                </tr>
                                {% empty %}
                                <tr>
                                    <td>
                                        <h5 class="font-weight-light" >No completed appointment </h5>
                                    </td>
                                </tr>

                                {% endfor %}

                                
                              
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
      
    </div>
</div>
{% endblock content %}
    